DEBUG:root:About to do f().
DEBUG:root:About to do h().
ERROR:root:division by zero
Traceback (most recent call last):
  File "c:\Users\Turner_prize\Documents\Python Projects\pythonLogging\main.py", line 25, in e
    f()
  File "c:\Users\Turner_prize\Documents\Python Projects\pythonLogging\main.py", line 4, in f
    return g()
  File "c:\Users\Turner_prize\Documents\Python Projects\pythonLogging\main.py", line 7, in g
    return h()
  File "c:\Users\Turner_prize\Documents\Python Projects\pythonLogging\main.py", line 11, in h
    return i()
  File "c:\Users\Turner_prize\Documents\Python Projects\pythonLogging\main.py", line 14, in i
    1/0
ZeroDivisionError: division by zero
